# Generated by Django 2.1.3 on 2018-12-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_key', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(choices=[(-3, 'down'), (-2, 'warning'), (-1, 'unknown'), (0, 'pending'), (1, 'healthy'), (2, 'starting'), (3, 'restart')], default=-1)),
                ('count_restart', models.PositiveIntegerField(default=0)),
                ('datetime_create', models.DateTimeField()),
                ('datetime_update', models.DateTimeField()),
                ('target_port', models.CharField(default='', max_length=10)),
                ('command', models.CharField(default='', max_length=255)),
                ('endpoint', models.CharField(default='', max_length=255)),
                ('meta_data', models.TextField(default='')),
            ],
        ),
    ]
