# Generated by Django 2.1.3 on 2018-12-03 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(-3, 'down'), (-2, 'warning'), (-1, 'unknown'), (0, 'pending'), (1, 'healthy'), (2, 'starting'), (3, 'restart')], default=0)),
                ('service_key', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('meta_data', models.TextField(default='')),
                ('datetime_update', models.DateTimeField()),
                ('datetime_create', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack_key', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField(default=0)),
                ('orchestrator', models.IntegerField(choices=[(1, 'docker'), (2, 'k8s')], default=1)),
                ('meta_data', models.TextField(default='')),
                ('datetime_update', models.DateTimeField()),
                ('datetime_create', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_docker.Stack'),
        ),
    ]
