# Generated by Django 2.1.3 on 2018-12-02 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_update', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('datetime_create', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('repository', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(default=0)),
                ('is_authenticate', models.BooleanField(default=False)),
                ('authenticate_username', models.CharField(default='', max_length=255)),
                ('authenticate_password', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Image'),
        ),
    ]
