# Generated by Django 2.1.3 on 2018-12-04 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_memory', models.PositiveIntegerField(default=0, max_length=90)),
                ('max_cpu', models.PositiveIntegerField(default=0, max_length=90)),
                ('min_memory', models.PositiveIntegerField(default=0)),
                ('min_cpu', models.PositiveIntegerField(default=0)),
                ('is_auto_scale', models.BooleanField(default=False)),
                ('max_scale', models.PositiveIntegerField(default=0)),
                ('min_scale', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controller.Controller')),
            ],
        ),
    ]
