# Generated by Django 2.1.3 on 2018-12-02 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cluster', '0002_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='cluster',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cluster.Cluster'),
        ),
    ]
